In [1]:
sc

In [2]:
#Loading the preprocessed complete movie data
import pandas as pd
complete_movies_preprocessed_data=pd.read_csv('complete_movies_processed_data.csv/part-00000',sep='::',names = ["movie_id", "title", "year", "genres"])

/home/ubuntu/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  app.launch_new_instance()

In [3]:
#Removing the movies whose release year was not available
import numpy as np
data_columns = ['year']
complete_movies_preprocessed_data = (complete_movies_preprocessed_data.drop(data_columns, axis=1)
         .join(complete_movies_preprocessed_data[data_columns].apply(pd.to_numeric, errors='coerce')))

In [4]:
#Converting the values of the column year to int
complete_movies_preprocessed_data=complete_movies_preprocessed_data[complete_movies_preprocessed_data[data_columns].notnull().all(axis=1)]
complete_movies_preprocessed_data['year']=complete_movies_preprocessed_data['year'].apply(lambda x:int(x))

In [5]:
complete_movies_preprocessed_data

,movie_id,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995
5,6,Heat,Action|Crime|Thriller,1995
6,7,Sabrina,Comedy|Romance,1995
7,8,Tom and Huck,Adventure|Children,1995
8,9,Sudden Death,Action,1995
9,10,GoldenEye,Action|Adventure|Thriller,1995
10,11,"American President, The",Comedy|Drama|Romance,1995
11,12,Dracula: Dead and Loving It,Comedy|Horror,1995
12,13,Balto,Adventure|Animation|Children,1995
13,14,Nixon,Drama,1995
14,15,Cutthroat Island,Action|Adventure|Romance,1995
15,16,Casino,Crime|Drama,1995
16,17,Sense and Sensibility,Drama|Romance,1995
17,18,Four Rooms,Comedy,1995
18,19,Ace Ventura: When Nature Calls,Comedy,1995
19,20,Money Train,Action|Comedy|Crime|Drama|Thriller,1995
20,21,Get Shorty,Comedy|Crime|Thriller,1995
21,22,Copycat,Crime|Drama|Horror|Mystery|Thriller,1995
22,23,Assassins,Action|Crime|Thriller,1995
23,24,Powder,Drama|Sci-Fi,1995
24,25,Leaving Las Vegas,Drama|Romance,1995
25,26,Othello,Drama,1995
26,27,Now and Then,Children|Drama,1995
27,28,Persuasion,Drama|Romance,1995
28,29,"City of Lost Children, The (Cit√© des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi,1995
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao),Crime|Drama,1995
...,...,...,...,...
45812,176205,Phobos. Fear Kills,Horror|Thriller,2010
45813,176207,The Final Storm,Action|Horror|Mystery|Thriller,2010
45814,176211,In a Heartbeat,Animation|Romance,2017
45815,176213,"Blood, Sweat and Tears",Drama,2015
45816,176215,Jungle Woman,Drama|Fantasy|Horror,1944
45817,176217,To Be Fat Like Me,Children|Drama,2007
45818,176219,Cadet Kelly,Comedy,2002
45819,176221,The Scheming Gambler's Paradise,(no genres listed),1905
45820,176223,The Man with the Rubber Head,Comedy|Fantasy|Sci-Fi,1901
45821,176225,The Living Playing Cards,Fantasy,1905
45822,176227,The Hilarious Posters,Comedy|Fantasy,1906
45823,176229,The Devilish Tenant,Comedy|Fantasy,1909
45824,176231,The Untameable Whiskers,(no genres listed),1904
45825,176233,The Imperceptable Transmutations,(no genres listed),1904
45826,176235,Pooh's Heffalump Halloween Movie,Animation|Children,2005
45827,176237,The One-Man Band,Action|Fantasy|Thriller,1900
45828,176239,The Fat and Lean Wrestling Match,Comedy|Fantasy,1900
45829,176245,Deep Hearts,Documentary,1981
45830,176249,Mom,Crime|Drama|Thriller,2017
45831,176251,The Morning After,Comedy|Drama,2015
45832,176253,St. Michael Had a Rooster,(no genres listed),1972
45833,176255,House of Horrors,Horror|Mystery|Thriller,1946
45834,176257,Shadow of the Blair Witch,Horror|Mystery,2000
45835,176259,The Burkittsville 7,Horror,2000
45836,176263,Caged Heat 3000,Sci-Fi,1995
45837,176267,Robin Hood,Action|Drama|Romance,1991
45839,176271,Century of Birthing,Drama,2011
45840,176273,Betrayal,Action|Drama|Thriller,2003
45841,176275,Satan Triumphant,(no genres listed),1917
45842,176279,Queerama,(no genres listed),2017

In [6]:
#Listing movies with genres listed as '(no genres listed)'
print ("Movies with 'genres' listed as '(no genres listed)' are ",len(complete_movies_preprocessed_data[complete_movies_preprocessed_data['genres']=='(no genres listed)']))

Movies with 'genres' listed as '(no genres listed)' are  2630

In [7]:
#removing the movies with genres listed as '(no genres listed)'
complete_movies_preprocessed_data=complete_movies_preprocessed_data[~(complete_movies_preprocessed_data['genres']=='(no genres listed)')]

In [8]:
#Saving the cleaned data in csv file
complete_movies_preprocessed_data.to_csv('complete_movies_cleaned.csv',sep='%')

In [9]:
#Loading the preprocessed complete ratings data
complete_ratings_preprocessed_data=pd.read_csv('complete_ratings_processed_data.csv/part-00000',sep='%',names = ['user_id','movie_id','rating','timestamp'])

In [15]:
#Converting the type of values in movie_id to int and storing the number of ratings per movie id in ratings_movie_id_len
complete_ratings_preprocessed_data['movie_id']=complete_ratings_preprocessed_data['movie_id'].astype(int)
ratings_movie_id_len=complete_ratings_preprocessed_data.groupby('movie_id').size()
complete_ratings_preprocessed_data

          user_id  movie_id  rating            timestamp
0               1       110     1.0  2015-03-09 22:52:09
1               1       147     4.5  2015-03-09 23:07:15
2               1       858     5.0  2015-03-09 22:52:03
3               1      1221     5.0  2015-03-09 22:52:26
4               1      1246     5.0  2015-03-09 22:52:36
5               1      1968     4.0  2015-03-09 23:02:28
6               1      2762     4.5  2015-03-09 22:48:20
7               1      2918     5.0  2015-03-09 22:53:13
8               1      2959     4.0  2015-03-09 22:53:21
9               1      4226     4.0  2015-03-09 23:03:48
10              1      4878     5.0  2015-03-09 22:50:34
11              1      5577     5.0  2015-03-09 22:49:57
12              1     33794     4.0  2015-03-09 23:00:05
13              1     54503     3.5  2015-03-09 22:48:33
14              1     58559     4.0  2015-03-09 23:00:07
15              1     59315     5.0  2015-03-09 22:51:42
16              1     68358     5.0  2015-03-09 22:51:04
17              1     69844     5.0  2015-03-09 23:02:19
18              1     73017     5.0  2015-03-09 23:11:39
19              1     81834     5.0  2015-03-09 23:02:13
20              1     91500     2.5  2015-03-09 23:10:47
21              1     91542     5.0  2015-03-09 23:10:18
22              1     92439     5.0  2015-03-09 22:50:24
23              1     96821     5.0  2015-03-09 22:49:42
24              1     98809     0.5  2015-03-09 23:10:40
25              1     99114     4.0  2015-03-09 22:54:27
26              1    112552     5.0  2015-03-09 22:48:56
27              2         5     3.0  1997-06-23 04:14:09
28              2        25     3.0  1997-06-23 04:12:48
29              2        32     2.0  1997-06-23 04:12:46
...           ...       ...     ...                  ...
26024259   270896     41566     3.5  2009-11-01 00:08:48
26024260   270896     44191     5.0  2009-10-31 23:25:46
26024261   270896     44195     4.0  2009-11-01 00:13:47
26024262   270896     45499     3.0  2009-11-01 00:08:51
26024263   270896     45722     3.5  2009-10-31 23:28:35
26024264   270896     46578     4.5  2009-11-01 00:07:17
26024265   270896     48385     4.0  2009-10-31 23:32:19
26024266   270896     48394     5.0  2009-10-31 23:31:01
26024267   270896     48516     4.5  2009-10-31 23:25:26
26024268   270896     48774     5.0  2009-10-31 23:34:00
26024269   270896     48780     5.0  2009-10-31 23:30:30
26024270   270896     49272     4.0  2009-10-31 23:24:34
26024271   270896     49530     4.0  2009-11-01 00:13:56
26024272   270896     50872     5.0  2009-11-01 00:06:40
26024273   270896     50954     2.5  2009-11-01 00:09:39
26024274   270896     51255     4.5  2009-11-01 00:05:27
26024275   270896     51662     4.5  2009-10-31 23:32:08
26024276   270896     52973     3.5  2009-11-01 00:12:05
26024277   270896     53996     3.0  2009-11-01 00:11:22
26024278   270896     54001     4.0  2009-11-01 00:12:11
26024279   270896     54286     4.5  2009-10-31 23:28:21
26024280   270896     54503     4.0  2009-11-01 00:04:46
26024281   270896     55820     5.0  2009-10-31 23:27:40
26024282   270896     56174     3.5  2009-11-01 00:08:05
26024283   270896     56367     4.5  2009-10-31 23:25:29
26024284   270896     58559     5.0  2009-10-31 23:26:04
26024285   270896     60069     5.0  2009-10-31 23:33:52
26024286   270896     63082     4.5  2009-10-31 23:29:24
26024287   270896     64957     4.5  2009-11-01 00:06:30
26024288   270896     71878     2.0  2009-10-31 23:30:58

[26024289 rows x 4 columns]

In [16]:
#Getting the user id who have rated just 1 movie
one_rating_index=[i+1 for i, x in enumerate(ratings_movie_id_len) if x == 1]
len(one_rating_index)

7659

In [17]:
#Getting movie ids which do have more than 1 ratings
movie_id_set = set(complete_ratings_preprocessed_data.movie_id)
one_rating_index_set = set(one_rating_index)
print(len(movie_id_set),len(one_rating_index_set),len(movie_id_set-one_rating_index_set))
result_set=movie_id_set-one_rating_index_set

45115 7659 44280

In [18]:
#Storing just the movies with more than 1 ratings and removing the rest
complete_ratings_cleaned=complete_ratings_preprocessed_data[complete_ratings_preprocessed_data.movie_id.isin(list(result_set))]

In [19]:
#Saving the cleaned data
complete_ratings_cleaned.to_csv('complete_ratings_cleaned.csv',sep='%')